version: "3.9"
   
services:
  db:
    image: postgres:14.3
    volumes:
      - mysite_db:/var/lib/postgresql/data
    env_file:
      - .env/db.env
    ports:
      - "5432:5432"
    
  web:
    build: .
    command: tail -f /dev/null
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "5678:5678"
    env_file:
      - .env/web.env
    depends_on:
      - db
  
volumes:
  mysite_db: